### ISSUE TITLE
Can't submit a bug

### ISSUE THREAD

**Issue by jplevene** [jquery/jqueryui.com#108]
I keep getting the error

Submission rejected as potential spam (Maximum number of posts per hour for this IP (127.0.0.1) exceeded)

My IP address is not even 127.0.0.1

Bug I'm trying to post for ui dialog on latest jquery ui on stable release is:

Really minor bug on Firefox only.

SCENARIO: You have a <div> inside a dialog that is a vertical resizeable or changes size after the dialog is opened.

If the dialog is NOT moved/dragged after being opened, the resizing of the <div> resizes the height of the dialog as it should, however if you move/drag the dialog then change the height of the <div>, the dialog fails to resize correctly.

If you close and then reopen the dialog, the dialog has resized correctly, but still does not resize correctly if its contents is resized.

This only happens on Firefox (tested on 37.0.1 on Windows 7 32 bit), works fine on Chrome and IE.

----

[http://jsfiddle.net/jplevene/pgo3stku/]

**Comment by scottgonzalez** [comment]
http://bugs.jqueryui.com/ticket/10725
