### ISSUE TITLE
Minor correction in documentation - datasource is geobytes.com and not geonames.org

### ISSUE THREAD

**Issue by Herzo** [jquery/jqueryui.com#109]
Minor correction for the documentation at http://jqueryui.com/autocomplete/#remote-jsonp - the datasource that the sample is using is actually http://gd.geobytes.com/AutoCompleteCity so accordingly  where it says "Powered by geonames.org" it should say "Powered by geobytes.com".

Thanks heaps for your assistance.

**Comment by scottgonzalez** [comment]
Thanks, but this needs to be fixed in https://github.com/jquery/jquery-ui, which is the source of the demos.

**Comment by jzaefferer** [comment]
Thats not the only thing wrong with that demo. I'm putting together a patch.
