### ISSUE TITLE
`Sortable` examples include `disableSelection()`

### ISSUE THREAD

**Issue by jhfrench** [jquery/jqueryui.com#116]
Within the [sortable() documentation](http://jqueryui.com/sortable/), all of the examples (except "Portlets") include `disableSelection()`.

The documentation for `disableSelection()` says:

> Disabling text selection is bad. Don't use this.

**Comment by arthurvr** [comment]
Besides from just being evil, that method is deprecated too (see [#7755](http://bugs.jqueryui.com/ticket/7755)), so yes, we shouldn't be doing it in our examples too. Thanks for the report.

> Within the sortable() documentation

It's used in some [other demos](https://github.com/jquery/jquery-ui/search?utf8=%E2%9C%93&q=disableSelection%28%29%3B&type=Code) too.

**Comment by scottgonzalez** [comment]
Yes, it's deprecated and it's bad, but we're not dropping it until the rewrites land since the interactions need to be updated first. Also, this applies to more than just sortable and all of the code lives in the jquery-ui repo, not this repo.
