### ISSUE TITLE
Requests blocked over https

### ISSUE THREAD

**Issue by Nicrob64** [jquery/jqueryui.com#118]
The page https://api.jqueryui.com/color-animation/ tries to load the js/css via http so the requests get blocked. Console log is below

Log:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

color-animation.html:6 Mixed Content: The page at 'https://api.jqueryui.com/resources/color-animation.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css'. This request has been blocked; the content must be served over HTTPS.

color-animation.html:1 Mixed Content: The page at 'https://api.jqueryui.com/resources/color-animation.html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.10.2.js'. This request has been blocked; the content must be served over HTTPS.

color-animation.html:1 Mixed Content: The page at 'https://api.jqueryui.com/resources/color-animation.html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/ui/1.11.4/jquery-ui.js'. This request has been blocked; the content must be served over HTTPS.

color-animation.html:25 Uncaught ReferenceError: $ is not defined

**Comment by arthurvr** [comment]
>  https://api.jqueryui.com/color-animation/

Mind reopening this issue at the api.jqueryui.com repo? This is the issue tracker for the *jqueryui.com* site. Thanks :)

**Comment by jzaefferer** [comment]
Fixed via https://github.com/jquery/api.jqueryui.com/commit/1b4ee81670c46e4275e7a802710e1f3cb2631f2e (messed up the commit message)
