### ISSUE TITLE
Can't submit a jQuery UI bug

### ISSUE THREAD

**Issue by RandScullard** [jquery/jqueryui.com#122]
I'm trying to submit a jQuery UI bug via http://bugs.jqueryui.com/newticket. When I click Create Ticket, I get the following error:

> Submission rejected as potential spam (Maximum number of posts per hour for this IP (127.0.0.1) exceeded)

Something is clearly broken with the spam filter -- look at that IP address.

**Comment by scottgonzalez** [comment]
This in an intermittent, but frequent, problem. We're in the process of upgrading Trac which should resolve the issue. Since that's a fairly major project that's already being tracked elsewhere and there's nothing we can do as an interim fix, I'm going to close this issue.
