### ISSUE TITLE
theme-roller not honoring edited font-size

### ISSUE THREAD

**Issue by cdaringe** [jquery/jqueryui.com#136]
Hi all:

I have made a custom theme using theme roller.  Changing from the default font-size of 1.1em to ~any other value does not appear to be honored.  Upon review of the freshly downloaded archive, my css files do not have the requested font-size value.  I have tried a myriad of values, and tried different units, em and px.  Other exported changes appear to be working as expected.

Thanks,

Chris

**Comment by cdaringe** [comment]
For ref, my base theme is [here](http://jqueryui.com/themeroller/?ffDefault=Helvetica&fwDefault=normal&fsDefault=1em&cornerRadius=3px&bgColorHeader=%23f9f9f9&bgTextureHeader=flat&bgImgOpacityHeader=100&borderColorHeader=%23aaaaaa&fcHeader=%23222222&iconColorHeader=%23222222&bgColorContent=%23ffffff&bgTextureContent=flat&bgImgOpacityContent=75&borderColorContent=%23aaaaaa&fcContent=%23222222&iconColorContent=%23222222&bgColorDefault=%23fdfdfd&bgTextureDefault=flat&bgImgOpacityDefault=100&borderColorDefault=%23aaaaaa&fcDefault=%23333333&iconColorDefault=%23454545&bgColorHover=%23e6e6e6&bgTextureHover=flat&bgImgOpacityHover=75&borderColorHover=%23999999&fcHover=%23212121&iconColorHover=%23454545&bgColorActive=%23eeeeee&bgTextureActive=inset_hard&bgImgOpacityActive=100&borderColorActive=%23aaaaaa&fcActive=%23212121&iconColorActive=%23454545&bgColorHighlight=%23fbf9ee&bgTextureHighlight=glass&bgImgOpacityHighlight=55&borderColorHighlight=%23fcefa1&fcHighlight=%23363636&iconColorHighlight=%232e83ff&bgColorError=%23fef1ec&bgTextureError=glass&bgImgOpacityError=95&borderColorError=%23cd0a0a&fcError=%23cd0a0a&iconColorError=%23cd0a0a&bgColorOverlay=%23aaaaaa&bgTextureOverlay=flat&bgImgOpacityOverlay=0&opacityOverlay=30&bgColorShadow=%23aaaaaa&bgTextureShadow=flat&bgImgOpacityShadow=0&opacityShadow=30&thicknessShadow=3px&offsetTopShadow=-3px&offsetLeftShadow=-3px&cornerRadiusShadow=3px)

**Comment by jzaefferer** [comment]
@cdaringe I just clicked on your base theme link and got a theme rendered with 1em. I then clicked on "Download theme", "Download" once more, unpacked the zip, looked at the index.html and got the same font size there. I also tried the same thing with font-size 2em, and it also worked fine.

Can you see if you can still reproduce the issue? If so, can you tells us what browser you're using? Where are you seeing the bad font-size?

**Comment by cdaringe** [comment]
:open_mouth:
@jzaefferer, it's ...working!  I wonder what happened/changed?  Thanks for following up!
