### ISSUE TITLE
Error in demo page

### ISSUE THREAD

**Issue by carloton** [jquery/jqueryui.com#142]
Hi, in the page: https://jqueryui.com/datepicker/
i get a 404 error using chrome developer tools: 

Request URL:
https://jqueryui.com/resources/demos/bootstrap.js
Request Method:
GET
Status Code:
404 Not Found

![jquery_bootstrap_error_404](https://cloud.githubusercontent.com/assets/16714712/12346315/0eaeb0fe-bb19-11e5-8abb-0bf9a1608827.png)

**Comment by johnsonz** [comment]
I met this problem today too. All jquery ui demos can not be demonstrated.

**Comment by sleslie321** [comment]
https://jqueryui.com/autocomplete/ also same problem

**Comment by jzaefferer** [comment]
Thank you for the report. We had a bad deploy and are working on a fix.

**Comment by jzaefferer** [comment]
Demos are working again.
