### ISSUE TITLE
Please improve the navigation on *jqueryui.com.

### ISSUE THREAD

**Issue by GSPP** [jquery/jqueryui.com#148]
Navigation is so unintuitive that I'm taking the time to write this issue. I often find myself to be helpless to find the page I want.

1. On http://api.jqueryui.com/autocomplete/ I can't reach the samples (http://jqueryui.com/autocomplete/).
2. On the samples page (http://jqueryui.com/autocomplete/) the link to the documentation is hidden in text that nobody reads.
3. When on http://jqueryui.com/autocomplete/ I find it quite hard to find out how to actually use jQuery UI. Clicking "API Documentation" leads to a maze of links that lead nowhere. The only way to reach the page is the start page (http://jqueryui.com/), then clicking "getting started guide" which is burried in text that nobody reads.

In case you think "you need to read the text": Users *should not need to* read the text for basic use cases.

My suggestion: Make *all* pages into a tree and show the tree on the left at all times. Don't create any "clever" or contextual navigation. Just show the tree of pages at all times.

**Comment by scottgonzalez** [comment]
Sorry, but a full page site tree will never make it into the sidebar. If you'd like to provide other suggestions, we can discuss. But a single issue for revamping all navigation and cross-linking isn't helpful.

**Comment by GSPP** [comment]
Alright, scratch that suggestion. Instead I request that you fix these *significant* problems in any way you see fit.

What is your opinion on this? You have closed the issue based on the fact that my suggestion is not possible to implement (I agree). But are you not agreeing that the navigation is not good as it stands?

**Comment by scottgonzalez** [comment]
> On http://api.jqueryui.com/autocomplete/ I can't reach the samples (http://jqueryui.com/autocomplete/).

See https://github.com/jquery/api.jqueryui.com/issues/176

> On the samples page (http://jqueryui.com/autocomplete/) the link to the documentation is hidden in text that nobody reads.

Suggestions? Would it help if we move the link above the iframe?

> When on http://jqueryui.com/autocomplete/ I find it quite hard to find out how to actually use jQuery UI.

That's fairly vague about what you're trying to figure out. Without more info, we can't possibly lead you to the right place. Are you looking for intro material such as http://learn.jquery.com/jquery-ui/, are you looking for API docs, are you looking for a list of components?

> Clicking "API Documentation" leads to a maze of links that lead nowhere.

It leads to the home page of api.jqueryui.com. From there you can use the navigation links in the sidebar or use the search.

> The only way to reach the page is the start page (http://jqueryui.com/), then clicking "getting started guide" which is burried in text that nobody reads.

Surely we can't link to the getting started guide from every page. Do you have reasonable suggestions for this? Do you have other projects that you can link to that provide better navigation to such material from a demo page?

**Comment by GSPP** [comment]
Here's a sketch for the autocomplete navigation:

![image](https://cloud.githubusercontent.com/assets/12032350/15391697/06bfb5fc-1dc3-11e6-8476-dea59d9e092a.png)

Here's something for the API site:

![image](https://cloud.githubusercontent.com/assets/12032350/15391749/59e1830a-1dc3-11e6-9ee3-fe84c28e1cd4.png)


Changes are marked. Just put all important pages on the left and pin them there so that they are visible on all pages. Context based navigation can be quite confusing. It's a means of last resort if space runs out.

**Comment by GSPP** [comment]
What's the status of this? The navigation remains unintuitive. Issue (2) has become worse: The demos link has disappeared entirely.

Go to http://api.jqueryui.com/autocomplete/ and try to:

1. Notice, that demos even *exist*
2. Find the demos

You will fail at at both. **Does the team consider this an adequate navigation?**

**Comment by GSPP** [comment]
An example for good documentation was requested. I think [https://simpleinjector.readthedocs.io/en/latest/index.html](url) is really nice. Mainly, because it is so easy to see what documents are *available*. You don't get lost.
