### ISSUE TITLE
What was the previous repo of the jquery ui npm package? 

### ISSUE THREAD

**Issue by b3njamin** [jquery/jqueryui.com#150]
The build that has been pushed to NPM is different to previous builds and and breaks various when used with browserify. There is no clear path to upgrade and as jQuery UI doesn't use semver it allows this update breaks when running npm update. 

PS sorry for posting in a seemingly random place - I cant figure where the active community discuss / report issues. IRC was empty.

**Comment by jzaefferer** [comment]
The previous repo was https://github.com/devongovett/jqueryui-npm

There's a demo for using the npm package with webpack: https://github.com/jzaefferer/webpack-jquery-ui

When I built that demo, I also tried to make it work with browserify, but got stuck on this issue, which was never resolved: https://github.com/jaredhanson/deamdify/issues/33

If switching to webpack isn't an option, maybe resolving that deamdify issue will help?

Either way, would be good to extend http://jqueryui.com/upgrade-guide/1.12/ for others having the same issue.

PS: The regular place to report bugs for jQuery UI is https://bugs.jqueryui.com/

**Comment by scottgonzalez** [comment]
Knowing that jQuery UI doesn't use semver yet, you should use appropriate ranges in `package.json`.

**Comment by jzaefferer** [comment]
Reopening this, since we should extend the upgrade guide for this.

* Get rid of minor version range in your package.json to avoid accidental upgrade
* When you want to upgrade, replace `require('jquery-ui/autocomplete')` with `require('jquery-ui/autocomplete')`. 
* If you use `require('jquery-ui')`, you have to replace that with individual require calls like `require('jquery-ui/autocomplete')`

It would be nice to have a working demo with browserify. https://github.com/jzaefferer/browserify-jquery-ui is a good start. Need help to get that working.

Should also mention this in http://learn.jquery.com/jquery-ui/environments/amd/

**Comment by jzaefferer** [comment]
Also documented that browserify isn't working, thanks to deamdify not working with UMD:

> This is a problem with browserify (it works fine with webpack: ​https://github.com/jzaefferer/webpack-jquery-ui ). For browserify, you need to use the deamdify plugin, but that is buggy: ​https://github.com/jaredhanson/deamdify/issues/33 There's a recent PR for that issue, might be worth testing or helping to finish that: ​https://github.com/jaredhanson/deamdify/pull/39

From https://bugs.jqueryui.com/ticket/15015

**Comment by marlun** [comment]
Will https://github.com/jaredhanson/deamdify/commit/1c24d28817ae46ff7ea24ba74fde18f0e1c3e64a commit to deamdify solve this?

**Comment by jzaefferer** [comment]
It might! If you're interested, you could file an issue on https://github.com/jzaefferer/browserify-jquery-ui and/or a PR to update deamdify there. If we can get the demo to work, we could update the upgrade guide again.

**Comment by bs-thomas** [comment]
For the latest JQuery UI 1.12.1, this is what I did and seemed to work for me with browserify:

var $ = require('jquery');
$.ui = require('jquery-ui/ui/widget.js');

Not sure if it's the right way to do it.  If not, please do point out, as I'm using this on production and I definitely want to be on the safe side.
