### ISSUE TITLE
No blog entry for jQueryUI 1.12.0

### ISSUE THREAD

**Issue by m-berling** [jquery/jqueryui.com#154]
I have almost missed that jQueryUI 1.12.0 has finally been released. Unlike for previous releases, there is no entry on the jQueryIU blog; last entry is for 1.12.0 RC 2 only (from April 21).

I'd suppose I am not the only one who relies on the blog for news regarding new releases, so maybe you like to drop a short note there.

BTW, thanks a lot for your work on jQueryUI!

**Comment by scottgonzalez** [comment]
It was intentionally not announced. Please wait for the next release.
