### ISSUE TITLE
API documentation missing some widgets

### ISSUE THREAD

**Issue by DavidEgolf** [jquery/jqueryui.com#157]
The widgets [(http://api.jqueryui.com/category/widgets/)](http://api.jqueryui.com/category/widgets/) page is missing entries for the  Checkboxradio and Controlgroup widgets. Strangely, they appear on the 1.12 specific documentation widgets page [(http://api.jqueryui.com/1.12/category/widgets/)](http://api.jqueryui.com/1.12/category/widgets/). Not sure if intended behavior or bug.

This also creates issues when clicking the link for API Documentation in said widgets' demos.

**Comment by scottgonzalez** [comment]
This is mostly just the home page lying to you. There are several repos involved in the content of that site. The most notable being the [api.jqueryui.com repo](https://github.com/jquery/api.jqueryui.com), which contains all the content. However, the content for the home page is bundled into the [jquery-wp-content repo](https://github.com/jquery/jquery-wp-content/blob/master/themes/api.jqueryui.com/index.php). The jquery-wp-content change to list 1.12 as recent is live, but the 1.12 docs have not yet been marked to go to the main (unversioned) site.

**Comment by scottgonzalez** [comment]
The deployments have been set up.
