### ISSUE TITLE
themeroller not working properly

### ISSUE THREAD

**Issue by dhansmair** [jquery/jqueryui.com#159]
On the jQuery UI themeroller, the button icons sometimes appear in grey, sometimes in white.
But it is not possible to change the buttons icon color when you edit "clickable: default state" > icon.
Editing "clickable: hover state" > icon, the default state icon color can be changed, but not the hover state.
I have tried it in IE and Firefox.

**Comment by scottgonzalez** [comment]
Which button icons? Everything seems to be working correctly for me.

**Comment by dhansmair** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/21751746/18205594/1a651468-7123-11e6-9ca9-7e704e04a390.PNG)

I am not able to change the color of the Framework icons :-(
Not sure if it's a bug or I'm just wrong...
