### ISSUE TITLE
Position always down when open datapicker like Bootstrap datepicker Orientation Down

### ISSUE THREAD

**Issue by theromie** [jquery/jqueryui.com#162]
When i click on datepicker its open above input box for smaller resolution. but i always want to open down orientation like have in bootstrap datepicker.

**Comment by theromie** [comment]
Why you closed man @scottgonzalez

**Comment by scottgonzalez** [comment]
You filed the exact same bug in the correct bug tracker just minutes apart. I figured you would know why the one in the wrong repo was closed.
