### ISSUE TITLE
 Nginx version disclosure via forbidden Page

### ISSUE THREAD

**Issue by Sajibekanti** [jquery/jqueryui.com#163]
Hello 
I am Sajibe kanti 
I Have Found A Bug on your Web .

Vulnerability : Nginx version disclosure via forbidden Page

This information might help an attacker gain a greater understanding of the systems in use and potentially develop further attacks targeted at the specific version of Nginx.

Impact: 
An attacker might use the disclosed information to harvest specific security vulnerabilities for the version identified.

Steps to reproduce:

Go to http://jqueryui.com/jquery-wp-content/themes/jqueryui.com/i/

Now the nginx version shows in bottom.

Reference : https://hackerone.com/reports/194319

Thanks 
Sajibe Kanti

**Comment by scottgonzalez** [comment]
I've filed an issue for the infrastructure team.

**Comment by Sajibekanti** [comment]
Reward or Credit ?

**Comment by scottgonzalez** [comment]
Sorry, we don't do that.

**Comment by Sajibekanti** [comment]
So 
I Can Get Credit

**Comment by scottgonzalez** [comment]
I'm not sure what you mean. Do you want us to publicly acknowledge your report?

**Comment by Sajibekanti** [comment]
yes 
you understood
