### ISSUE TITLE
Effect demo bug

### ISSUE THREAD

**Issue by CristhianUNSa** [jquery/jqueryui.com#164]
I think there is a bug when clicking the div more than once. Let's say, double or triple click... It appears to be creating divs when applying the effect. Here is the [link](http://api.jqueryui.com/effect/)

**Comment by scottgonzalez** [comment]
I'm not sure why you would think that clicking the div twice results in the effect running twice would be a bug.

**Comment by CristhianUNSa** [comment]
@scottgonzalez  Screen attached. An image worth a thousand words
![jqueryui-bug](https://user-images.githubusercontent.com/12214429/26989899-31f23bda-4d2b-11e7-81e5-a6c335121822.png)

**Comment by scottgonzalez** [comment]
I've filed a bug against jQuery UI: https://bugs.jqueryui.com/ticket/15203
