### ISSUE TITLE
Jquery library issues

### ISSUE THREAD

**Issue by SambharSurya** [jquery/jqueryui.com#166]
In my application I used Jquery and bootstrap related library files and my application is totally working fine before few months back but recently we are facing Jquery files related issues while running the application in IE , nothing did any changes in library files now but still errors. Please go through the attached file for errors .
 Due to this JQ errors I am unable to debugging my application please provide me a solution . I included latest version on JS library packages also from Nu get but still facing same issues .Thanks and please help us.
[js errors.txt](https://github.com/jquery/jqueryui.com/files/1266227/js.errors.txt)

**Comment by scottgonzalez** [comment]
A few things:

1. This bug tracker is for jqueryui.com, the website, not jQuery UI.
2. jquery-1.8.2.js is absolutely not the latest version.
3. This is not possible for us to debug.
