### ISSUE TITLE
jQuery UI Position issue with hidden elements

### ISSUE THREAD

**Issue by hubocan** [jquery/jqueryui.com#171]
Position is not set properly when the destination element is hidden.

**Comment by hubocan** [comment]
Related issue is when hidden element is shown using:
```
.toggle({
            duration: "fast",
            effect: "fade"
         }).position({
            my: "right top",
            at: "right bottom",
            of: this
         });
```
Position is lost after the effect animation completes. If the effect property is not set, the default effect is used and position is properly set even when effect animation completes.

**Comment by mgol** [comment]
This is a documentation repo. jQuery UI issues should be reported at https://bugs.jqueryui.com/.
