### ISSUE TITLE
tabs.js ajax issue

### ISSUE THREAD

**Issue by NotIT** [jquery/jqueryui.com#175]
Had a strange issue that whenever using the tabs.js feature on a page that got called with url parameters, the page would recursively make ajax calls over and over again to the same page. So, domain.com/url? would break, without the ? works fine. Tracked it down to the _ajaxSettings function but couldn't fix it. A temporary fix was made by modifying the _isLocal function regex from /#.*$/ to /(#|\?).*$/

**Comment by scottgonzalez** [comment]
Query strings are part of what defines the page. You should not be modifying `_isLocal`. However, this is the bug tracker for the web site only, not for jQuery UI itself.
