### ISSUE TITLE
[www][forum] jquery forum redricted do blank page after login.

### ISSUE THREAD

**Issue by Roinoss** [jquery/jqueryui.com#179]
After entering to jquery forum i'm redricted to blank page.

Login page: https://accounts.zoho.com/signin?servicename=ZohoDiscussions&serviceurl=https%3A%2F%2Fforum.jquery.com

After login im redircted to blank page and same when i open jquery forum.

Browsers: Firefox, Chrome

Redricted to (|replaced|):
https://forum.jquery.com/oauthorize?state=https|some numbers and %s|forum.jquery.com&ticket=|some numbers|&remember=-1

Page code source:
nothing here

No redircting on direct topic pages like:
https://forum.jquery.com/topic/jquery-validate-how-to-validate-hidden-input-value

**Comment by Roinoss** [comment]
Yes

**Comment by mgol** [comment]
jQuery Forums are read-only now, closing,
