### ISSUE TITLE
502 Bad gateway on trying to load upgrade-guide pages

### ISSUE THREAD

**Issue by ultraviola** [jquery/jqueryui.com#182]
I'm trying to research a version upgrade and have come across several pages consistently returning a 502 (Bad gateway).

For example:
- https://jqueryui.com/upgrade-guide/
- https://jqueryui.com/upgrade-guide/1.12/

Workaround: You can access the markdown for the page directly from github. For example: https://github.com/jquery/jqueryui.com/blob/master/page/upgrade-guide/1.12.md
You can see the list of upgrade-guides here:
https://github.com/jquery/jqueryui.com/blob/master/page/upgrade-guide/

**Comment by jwk15** [comment]
The outages seem to be spreading sporadically throughout the website. For example, I got a 504 from https://api.jqueryui.com/dialog/, but it's back today.

**Comment by jwk15** [comment]
502: https://jqueryui.com/selectmenu/
504: https://jqueryui.com/widget/

Clicking on the links on the right rail, it looks like roughly a fifth of the pages are having problems.

**Comment by jwk15** [comment]
502: https://jqueryui.com/position/

**Comment by mgol** [comment]
This seems to work fine now.
