### ISSUE TITLE
download.jqueryui.com throwing errors

### ISSUE THREAD

**Issue by robertmaxrees** [jquery/jqueryui.com#183]
Trying to download using the download builder takes you to a Cloudflare page saying that the host is throwing a 521.

**Comment by BearlyDoug** [comment]
It's actually been down since late Friday evening/early Saturday (US EDT)

Error 521
Ray ID: 5e4ed40f7a21d314 • 2020-10-20 01:05:03 UTC
Web server is down

**Comment by mgol** [comment]
This should be working fine now.
