### ISSUE TITLE
Those IE version checks at the start of the HTML seem to be invalid...

### ISSUE THREAD

**Issue by C80** [jquery/jqueryui.com#188]
Most jqueryui.com pages i've went to start with something like this:

```
<!--[if IE 7 ]>		 <html class="no-js ie ie7 lte7 lte8 lte9"> lang="en-US"> <![endif]-->
<!--[if IE 8 ]>		 <html class="no-js ie ie8 lte8 lte9"> lang="en-US"> <![endif]-->
<!--[if IE 9 ]>		 <html class="no-js ie ie9 lte9"> lang="en-US"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
```

Which includes a LOT of misplaced ">" characters, and would show up on screen for some browsers:
![image](https://user-images.githubusercontent.com/2808954/105861673-a5505c00-5ff7-11eb-98fa-181460d168ea.png)

**Comment by mgol** [comment]
Thanks for the report. I've removed the IE conditional headers now, they're not really needed anymore.
