### ISSUE TITLE
jQuery UI Css Link incorrect in the view source example code

### ISSUE THREAD

**Issue by WarriorofZarona** [jquery/jqueryui.com#205]
Currently the code is like so:

`<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">`

It is missing `https:` so it is screwing up with anyone trying to copy and paste the code, the resource isn't loading properly.

**Comment by mgol** [comment]
I transferred the issue to the correct repository.

**Comment by mgol** [comment]
This was fixed in https://github.com/jquery/jqueryui.com/commit/7945c962eeb513a0dd28506bf2f48a3f28a7cd4f. Also, see a duplicate issue here: https://github.com/jquery/jquery-ui/issues/2183
