### ISSUE TITLE
Creating an .everyN() traversal method

### ISSUE THREAD

**Issue by GloriaNOnwuneme** [jquery/jqueryui.com#213]
Dear team,

I'm Gloria, an aspiring web developer. Yesterday, I opened a pull request about adding an .everyN() traversal method. I forked (?) your repository and named it GloriaNOnwuneme-major. Just checking that I went about it the right way :)

**Comment by mgol** [comment]
Hi Gloria! You'd also have to submit a pull request to the jQuery UI repository for us to see it in our project. However, we are not looking into adding new APIs like that, especially to jQuery UI. I'm going to close this issue then.
