### ISSUE TITLE
Allow editing of demos

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jqueryui.com#40]
We want to allow users to edit our demos to explore features. That could be completely custom on just our own site, or a "Edit on jsfiddle" (or jsbin) link that creates a fresh fiddle/bin with the content of the demo, ready for the user to play with.

We don't want to deploy our content to other sites, so creating something on fiddle/bin should only happen on a user action.

**Comment by scottgonzalez** [comment]
Closing in favor of the more general issue for now: #96
