### ISSUE TITLE
Grunt tasks: Better error report

### ISSUE THREAD

**Issue by rxaviers** [jquery/jqueryui.com#93]
Currently, when a grunt task fails (for instance, `grunt deploy` / `grunt build-download`), error output is so reduced (if not absent at all) which doesn't help to debug. For example: https://gist.github.com/scottgonzalez/25a2fdf8238d8c85d5fe

Can we make it more verbose?

**Comment by jzaefferer** [comment]
This is still not perfect (see #127), but overall much better.
