### ISSUE TITLE
Incorrect link in effects demos

### ISSUE THREAD

**Issue by agcolom** [jquery/jqueryui.com#94]
All pages under the Effect category link the 1st item 'Effect demo' to http://jqueryui.com/resources/demos/effect/default.html which seems to get redirected to http://jqueryui.com/default instead of http://jqueryui.com/effect/ 

For example, go to http://jqueryui.com/addClass/ and click the 1st link in the top right corner just below 'Examples'.

**Comment by sammyshj** [comment]
I would like to work on this issue. @agcolom I can recreate this on my machine. Is anyone else working on this at the moment?

**Comment by scottgonzalez** [comment]
@sammyshj Nobody is working on this. Feel free to send a pull request.

**Comment by ashg1910** [comment]
@scottgonzalez I submitted a fix here - https://github.com/jquery/jquery-wp-content/pull/349
please check.
